---
- name: Dig Hum Box provisioning playbook
  hosts: all
  tasks:
    - name: Update package catalog
      become: true
      apt:
        update_cache: yes
    - name: Install dev tools
      become: true
      apt:
        name: build-essential
        state: present
    - name: Install database
      become: true
      apt:
        name:
          - postgresql
          - postgresql-client
        state: present
    - name: Install python
      become: true
      apt:
        name:
          - python3
          - python3-dev
          - python-is-python3
          - python3-pip
          - python3-django
          - python3-psycopg2
        state: latest
    - name: Install web server
      become: true
      apt:
        name: apache2
        state: present
    - name: Set up web server to run
      service:
        name: apache2
        enabled: yes
        state: started
    - name: Set up database to run
      service:
        name: postgresql
        enabled: yes
        state: started
